const rir_default_cfg = {
    ready: null,
    version: '0',
    userid: null,
    pmInboxInitialized: false,
    migratedToDB2: false,
    inboxRequestSize: 100,
    maxContacts: 50,
    contactSorting: 'getMostPopular',
    maxInitialMessagesShown: 50,
    updatePopularInterval: 60 * 60 * 24,
    updateInboxInterval: 60,
    lastUpdatePopular: 0,
    lastUpdateFriends: 0,
    lastUpdateBlocked: 0,
    lastUpdateInbox: 0,
    show_friends_first: 0,
    pageTitle: 'reddit.com: Revamped inbox',
    showModmail: true,
    conversationNewToOld: false,
    enhancedVisibility: false,
    deleteDraftAfterDays: 60,
    showDraftIndicator: true,
    doImport: true,
    rememberInputheight: false,
    inputHeight: 80,
    maxAjaxRetries: 5,
    ajaxRetryDelay: 5,
    max403Retries: 15
};
